options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/${PROJECT_ID}/gcp-devops-repo/gcpdevops-prod:${SHORT_SHA}"

steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "${_IMAGE_NAME}"
      - "."

  # Step 2: Push image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "${_IMAGE_NAME}"

  # Step 3: Replace image placeholder in gke.yaml
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed -i "s|__IMAGE__|${_IMAGE_NAME}|g" gke.yaml

  # Step 4: Deploy to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - "--image=${_IMAGE_NAME}"
      - "--location=us-central1-a"
      - "--cluster=gcp-devops-project"
      - "--namespace=development"
      - "--filename=gke.yaml"

